title: The Usual Suspects
description: Digitally Preserving Classic Synthesizers through Emulation
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github_username:
repository:
