title: The Usual Suspects
description: Digitally Preserving Classic Synthesizers through Emulation
github_username: dsp56300
repository: dsp56300/gearmulator
show_downloads: false

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

header_pages:
  - downloads/osirus.md
  - downloads/ostirus.md
  - downloads/vavra.md
  - downloads/xenia.md
  - downloads/je8086.md
  - downloads/nodalred2x.md
  - downloads/tus-tools.md
  - docs/installation-guide.md
  - docs/faqs.md
  - docs/demos.md
  - technical/osirus-c.md
  - blog.md
