title: The Usual Suspects
description: Digitally Preserving Classic Synthesizers through Emulation
github_username: dsp56300
repository: dsp56300/gearmulator
show_downloads: false

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

navigation:
  - title: Downloads
    children:
      - title: Osirus (Virus A/B/C)
        url: /downloads/osirus
      - title: OsTIrus (Virus TI)
        url: /downloads/ostirus
      - title: Vavra (microQ)
        url: /downloads/vavra
      - title: Xenia (MW II/XT)
        url: /downloads/xenia
      - title: JE8086 (JP-8000)
        url: /downloads/je8086
      - title: NodalRed2x (Nord Lead)
        url: /downloads/nodalred2x
      - title: TUS Tools
        url: /downloads/tus-tools
  - title: Documentation
    children:
      - title: Installation Guide
        url: /docs/installation-guide
      - title: FAQs
        url: /docs/faqs
      - title: Demos
        url: /docs/demos
      - title: VSTHost Configuration
        url: /docs/vsthost-configuration
      - title: Support Guide
        url: /docs/support-guide
  - title: Technical
    children:
      - title: Osirus C Technical Info
        url: /technical/osirus-c
  - title: Blog
    url: /blog
